### PR TITLE
Add per-repo user-specific diff statistics to graph output

### LINKED ISSUE #7: Add stats about lines by developer
The `get_contributors_commits_stats` HTTP request also gets data about lines added and removed (diff) by developers. Add these stats to the output and the graphs of #3

### PR DESCRIPTION
**Pull request by alecello**
A new graph is generated in each one of the per-repo figure with a bar graph containing the all-time and yearly diff statistics for each contributor for that specific repo.

The new graph is a stacked bar graph with two colors, the familiar green and red for added and removed lines.

### CODE REVIEW

**Comment by alecello** [comment]
Should close #7

**Comment by e-caste** [comment]
I see 3 issues in an example diff histogram here:
- one name does not display correctly
- many numbers are written on top of each other when the bars are short
- of the 3 numbers (deleted, added, total) I can only see the number of deleted lines and the total
Screenshot 2020-11-08 at 18 29 28

Could you address these issues?

**Comment by alecello** [comment]
Regarding point 3: There is no total, just deleted and created lines

**Comment by e-caste** [comment]
@alecello I believe it is not clear then. Best way is to change how the data is displayed, a number in the middle of the bar is not very readable

**Comment by alecello** [comment]
Ok, it's going to take __a lot__ more time than anticipated. Since I can't complete this right now (needs to rewrite a bunch of code), I'm marking this as draft until ready

**Pull request closed without merging**
